MusicCity/Areas/Admin/Controllers/BeatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCity.Areas.Admin.Controllers
{
    public class BeatController : Controller
    {
        // GET: Admin/Beat
        public ActionResult Index()
        {
            return View();
        }
    }
}

MusicCity/Areas/Admin/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCity.Areas.Admin.Controllers
{
    public class CountryController : Controller
    {
        // GET: Admin/Country
        public ActionResult Index()
        {
            return View();
        }
    }
}

MusicCity/Areas/Admin/Controllers/HipHopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCity.Areas.Admin.Controllers
{
    public class HipHopController : Controller
    {
        // GET: Admin/HipHop
        public ActionResult Index()
        {
            return View();
        }
    }
}

MusicCity/Areas/Admin/Controllers/InstrumentalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCity.Areas.Admin.Controllers
{
    public class InstrumentalController : Controller
    {
        // GET: Admin/Instrumental
        public ActionResult Index()
        {
            return View();
        }
    }
}

MusicCity/Areas/Admin/Controllers/POPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCity.Areas.Admin.Controllers
{
    public class POPController : Controller
    {
        // GET: Admin/POP
        public ActionResult Index()
        {
            return View();
        }
    }
}

MusicCity/Areas/Admin/Controllers/ParodyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCity.Areas.Admin.Controllers
{
    public class ParodyController : Controller
    {
        // GET: Admin/Parody
        public ActionResult Index()
        {
            return View();
        }
    }
}

MusicCity/Areas/Admin/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCity.Areas.Admin.Controllers
{
    public class ShopController : Controller
    {
        // GET: Admin/Shop
        public ActionResult Index()
        {
            return View();
        }
    }
}

MusicCity/Areas/Admin/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCity.Areas.Admin.Controllers
{
    public class VideoController : Controller
    {
        // GET: Admin/Video
        public ActionResult Index()
        {
            return View();
        }
    }
}

MusicCity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCity.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MusicCity/Areas/Admin/Views/Country/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

<h2>Index</h2>

MusicCity/Areas/Admin/Views/HipHop/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/AREAS/Admin/Views/Shared/_Layout.cshtml";

}

<h2>Index</h2>

MusicCity/Areas/Admin/Views/Instrumental/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";


}

<h2>Index</h2>

MusicCity/Areas/Admin/Views/POP/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

<h2>Index</h2>

MusicCity/Areas/Admin/Views/Parody/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

<h2>Index</h2>

MusicCity/Areas/Admin/Views/Video/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

<h2>Index</h2>

MusicCity/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MusicCity/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MusicCity/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="inSlider" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#inSlider" data-slide-to="0" class="active"></li>
        <li data-target="#inSlider" data-slide-to="1"></li>
    </ol>

    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <div class="container">
                <div class="carousel-caption">
                    <h1>
                        Optimal<br />
                        Nation<br />
                    </h1><br />
                    <p>You Are Welcome To The City Of Music</p>
                    <p>
                        <br /><br />

                        <a class="btn btn-lg btn-primary" href="@Url.Action("Register", "Account")" role="button">Sign Up</a>
                        <a class="btn btn-lg btn-primary" href="@Url.Action("Login", "Account")" role="button">Login</a>
                    </p>

                </div>
                <div class="carousel-image wow zoomIn">

                </div>
            </div>
            <!-- Set background for slide in css -->
            <img src="~/Content/Inspinia/img/landing/resize-15893865991430802841bannertitle4.jpg" />
        </div>
        <div class="carousel-item">
            <div class="container">
                <div class="carousel-caption blank">
                    <h1>We create awesome instrumentals <br /> Awesome jingles.</h1>
                    <p>We Write And Compose All Genres Of Original And Parody Songs.</p>
                    <a class="btn btn-lg btn-primary" href="@Url.Action("Register", "Account")" role="button">Sign Up</a>
                    <a class="btn btn-lg btn-primary" href="@Url.Action("Login", "Account")" role="button">Login</a>
                </div>
            </div>
            <!-- Set background for slide in css -->
            <img src="~/Content/Inspinia/img/landing/resize-15893865431048617657bannertitle1.jpg" />
        </div>
    </div>

    <a class="carousel-control-prev" href="#inSlider" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#inSlider" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<section id="features" class="container services">
    <div class="row">
        <div class="col-sm-3">
            <h2 style="color:yellowgreen">ROYALTY FREE MUSIC</h2>
            <p>Here are free sounds from different genres to get you grooving all day.</p>
            <p><a class="ladda-button btn btn-info" href="@Url.Action("Index", "Beat",new {area="Admin"})" role="button">MUSIC &raquo;</a></p>
        </div>
        <div class="col-sm-3">
            <h2 style="color:yellowgreen">SHOP</h2>
            <p> Kindly visit our store for our albums, EP's and many more.</p>
            <p><a class="ladda-button btn btn-info" href="@Url.Action("Index", "Shop",new {area="Admin"})" role="button">SHOP &raquo;</a></p>
        </div>
        <div class="col-sm-3">
            <h2 style="color:yellowgreen">TRAP/AFRO/COUNTRY</h2>
            <p>Here are free sounds from different genres to get you grooving all day.</p>
            <p><a class="ladda-button btn btn-info" href="@Url.Action("Index", "Beat",new {area="Admin"})" role="button">MUSIC &raquo;</a></p>
        </div>
        <div class="col-sm-3">
            <h2 style="color:yellowgreen">VIDEOS</h2>
            <p>Here are free sounds from different genres to get you grooving all day.</p>
            <p><a class="ladda-button btn btn-info" href="@Url.Action("Index", "Beat",new {area="Admin"})" role="button">VIDEOS &raquo;</a></p>
        </div>
    </div>
</section>



<section id="team" class="gray-section team">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>Our Team</h1>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 wow fadeInLeft">
                <div class="team-member">
                    <img src="~/Content/Inspinia/img/landing/avatar3.jpg" class="img-fluid rounded-circle img-small" alt="">
                    <h4><span class="navy">Amelia</span> Smith</h4>
                    <p>Lorem ipsum dolor sit amet, illum fastidii dissentias quo ne. Sea ne sint animal iisque, nam an soluta sensibus. </p>
                    <ul class="list-inline social-icon">
                        <li class="list-inline-item">
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="team-member wow zoomIn">
                    <img src="~/Content/Inspinia/img/landing/avatar1.jpg" class="img-fluid rounded-circle" alt="">
                    <h4><span class="navy">John</span> Novak</h4>
                    <p>Lorem ipsum dolor sit amet, illum fastidii dissentias quo ne. Sea ne sint animal iisque, nam an soluta sensibus.</p>
                    <ul class="list-inline social-icon">
                        <li class="list-inline-item">
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4 wow fadeInRight">
                <div class="team-member">
                    <img src="~/Content/Inspinia/img/landing/avatar2.jpg" class="img-fluid rounded-circle img-small" alt="">
                    <h4><span class="navy">Peter</span> Johnson</h4>
                    <p>Lorem ipsum dolor sit amet, illum fastidii dissentias quo ne. Sea ne sint animal iisque, nam an soluta sensibus.</p>
                    <ul class="list-inline social-icon">
                        <li class="list-inline-item">
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center m-t-lg m-b-lg">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p>
            </div>
        </div>
    </div>
</section>
<section id="testimonials" class="navy-section testimonials" style="margin-top: 0">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center wow zoomIn">
                <i class="fa fa-comment big-icon"></i>
                <h1>
                    What our users say
                </h1>
                <div class="testimonials-text">
                    <i>"Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."</i>
                </div>
                <small>
                    <strong>12.02.2014 - Andy Smith</strong>
                </small>
            </div>
        </div>
    </div>
</section>
<section class="comments gray-section" style="margin-top: 0">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>What our partners say</h1>
                <p>Donec sed odio dui. Etiam porta sem malesuada. </p>
            </div>
        </div>
        <div class="row features-block">
            <div class="col-lg-4">
                <div class="bubble">
                    "Uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
                </div>
                <div class="comments-avatar">
                    <a href="#" class="float-left">
                        <img alt="image" src="~/Content/Inspinia/img/landing/avatar3.jpg">
                    </a>
                    <div class="media-body">
                        <div class="commens-name">
                            Andrew Williams
                        </div>
                        <small class="text-muted">Company X from California</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="bubble">
                    "Uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
                </div>
                <div class="comments-avatar">
                    <a href="#" class="float-left">
                        <img alt="image" src="~/Content/Inspinia/img/landing/avatar1.jpg">
                    </a>
                    <div class="media-body">
                        <div class="commens-name">
                            Andrew Williams
                        </div>
                        <small class="text-muted">Company X from California</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="bubble">
                    "Uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
                </div>
                <div class="comments-avatar">
                    <a href="#" class="float-left">
                        <img alt="image" src="~/Content/Inspinia/img/landing/avatar2.jpg">
                    </a>
                    <div class="media-body">
                        <div class="commens-name">
                            Andrew Williams
                        </div>
                        <small class="text-muted">Company X from California</small>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<section id="contact" class="gray-section contact">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>Contact Us</h1>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.</p>
            </div>
        </div>
        <div class="row m-b-lg justify-content-center">
            <div class="col-lg-3 ">
                <address>
                    <strong><span class="navy">Company name, Inc.</span></strong><br />
                    Lagos<br />
                    Nigeria, CA 94107<br />
                    <abbr title="Phone">P:</abbr> (234) 7063262254
                </address>
            </div>
            <div class="col-lg-4">
                <p class="text-color">
                    Desmond<br/>
                    Super Island <br/>
                    Ikeja<br />
                    Lagos
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <a href="mailto:test@email.com" class="btn btn-primary">Send us mail</a>
                <p class="m-t-sm">
                    Or follow us on social platform
                </p>
                <ul class="list-inline social-icon">
                    <li class="list-inline-item">
                        <a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center m-t-lg m-b-lg">
                <p><strong>&copy; 2020 Company Name</strong><br /> consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p>
            </div>
        </div>
    </div>
</section>

MusicCity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<!-- Mirrored from webapplayers.com/inspinia_admin-v2.9.3/landing.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 May 2020 13:28:30 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Optimal Nation -City of Music</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/Inspinia/css/bootstrap.min.css" rel="stylesheet">
    <!-- Animation CSS -->
    <link href="~/Content/Inspinia/css/animate.css" rel="stylesheet">
    <link href="~/Content/Inspinia/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/Inspinia/css/style.css" rel="stylesheet">
</head>
<body id="page-top" class="landing-page no-skin-config">
    <div class="navbar-wrapper">
        <nav class="navbar navbar-default navbar-fixed-top navbar-expand-md" role="navigation">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Shop",new {area="Admin"})">VISIT OUR STORE</a>
                <div class="navbar-header page-scroll">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">

                        <i class="fa fa-bars"></i>
                    </button>
                </div>
                <div class="collapse navbar-collapse justify-content-end" id="navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="nav-link page-scroll" href="#page-top">Home</a></li>
                        <li><a class="nav-link page-scroll" href="#features">Features</a></li>
                        <li><a class="nav-link page-scroll" href="#team">Team</a></li>
                        <li><a class="nav-link page-scroll" href="#testimonials">Testimonials</a></li>
                        <li><a class="nav-link page-scroll" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderBody()
    <hr />

    <!-- Mainly scripts -->
    <script src="~/Content/Inspinia/js/jquery-2.1.1.js"></script>
    <script src="~/Content/Inspinia/js/jquery-3.1.1.min.js"></script>
    <script src="~/Content/Inspinia/js/popper.min.js"></script>
    <script src="~/Content/Inspinia/js/bootstrap.js"></script>
    <script src="~/Content/Inspinia/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/Content/Inspinia/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <!-- Custom and plugin javascript -->
    <script src="~/Content/Inspinia/js/inspinia.js"></script>
    <script src="~/Content/Inspinia/js/plugins/pace/pace.min.js"></script>
    <script src="~/Content/Inspinia/js/plugins/wow/wow.min.js"></script>

    <script>

        $(document).ready(function () {

            $('body').scrollspy({
                target: '#navbar',
                offset: 80
            });

            // Page scrolling feature
            $('a.page-scroll').bind('click', function (event) {
                var link = $(this);
                $('html, body').stop().animate({
                    scrollTop: $(link.attr('href')).offset().top - 50
                }, 500);
                event.preventDefault();
                $("#navbar").collapse('hide');
            });
        });

        var cbpAnimatedHeader = (function () {
            var docElem = document.documentElement,
                header = document.querySelector('.navbar-default'),
                didScroll = false,
                changeHeaderOn = 150;
            function init() {
                window.addEventListener('scroll', function (event) {
                    if (!didScroll) {
                        didScroll = true;
                        setTimeout(scrollPage, 150);
                    }
                }, false);
            }
            function scrollPage() {
                var sy = scrollY();
                if (sy >= changeHeaderOn) {
                    $(header).addClass('navbar-scroll')
                }
                else {
                    $(header).removeClass('navbar-scroll')
                }
                didScroll = false;
            }
            function scrollY() {
                return window.pageYOffset || docElem.scrollTop;
            }
            init();

        })();

        // Activate WOW.js plugin for animation on scrol
        new WOW().init();

    </script>
</body>
<!-- Mirrored from webapplayers.com/inspinia_admin-v2.9.3/landing.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 May 2020 13:29:31 GMT -->
</html>